---
apiVersion: v1
kind: Service
metadata:
 name: simpleflaskapp
spec:
 selector:
  name: simpleflaskapp
  app: simpleflaskapp
 ports:
 - protocol: TCP
   port: 80
   targetPort: 9299
   nodePort: 9999
 type: NodePort